# Site settings
title: eBusinessDev
email: tn76contact@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Web Design & Development 
  Fully Responsive Eye-Catching Solutions
  Client-focused, customer-centric, creating website solutions that deliver tangible business results,
  eBusinessDev’s web developers helps brands the ever-changing digital landscape.
  For the design and design and development of any tailored website contact us
  Let's get started.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Copyright &copy; 2014 - 2020
lang: en_US

# generate social links in footer
social_links:
  twitter: tn76com
  github:  tounsils
  # devto: jekyll
  # dribbble: jekyll
  # facebook: jekyll
  # flickr:   jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  # telegram: jekyll
  # googleplus: +jekyll
  # microdotblog: jekyll
  # keybase: jekyll

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compact
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/mmistakes
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/mmistakes
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/mmistakes
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
