# Site settings
title: eBusinessDev Web Applications dev
email: tn76contact@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Website design and development: website and web application design inspiration - Providing you new
  designs and web development, and offering the best web solutions for small to medium business.
baseurl: "" # the subpath of your site, e.g. /blog/
keywords: "Website design, eBusinessDev, tn76.com, tn76com, web design, Web Design and Development, best web design, best designs, best websites,
  responsive design, responsive design examples, best design awards, web 
  design awards, design awards, design inspiration, web design inspiration, 
  web design gallery, web design resources, web designer, web designers, small business, medium business 
  web designer directory, css gallery, wordpress themes, best wordpress themes, bootstrap, jquerry"
url: "https://www.tn76.com" # the base hostname & protocol for your site updated
author: Copyright &copy; 2014 - 2021
lang: en_US

# generate social links in footer +
social_links:
  twitter: tn76com
  github:  tounsils
  # devto: jekyll
  # dribbble: jekyll
  # facebook: jekyll
  # flickr:   jekyll
  # instagram: jekyll
  # linkedin: jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  # telegram: jekyll
  # googleplus: +jekyll
  # microdotblog: jekyll
  # keybase: jekyll

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compact
  precision: 10

#source: src
destination: ../public_html

collections:
  - products

#PAyment using paypal
payment:
  paypal:
    text: Pay Now      # Button text
    email: tn76contact@gmail.com  # PayPal button ID

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/tn76com
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/tn76com
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/tn76com
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
