name: Deploy to tn76com.github.io

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Sync files to tn76com.github.io
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git clone https://github.com/tn76com/tn76com.github.io.git
        rsync -av --progress ./ tn76com.github.io/ --exclude .git --exclude .github
        cd tn76com.github.io
        git add .
        git commit -m "Deploy"
        git push origin main
